name: Deploy

on: [push]

jobs:
  pack-unitypackage:
    runs-on: ubuntu-20.04
    name: Pack Unity Package
    if: github.event_name == 'push'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: release_pipeline
          fetch-depth: 0
      - name: Find all meta files
        run: |
          git mv Assets temp
          mkdir Assets
          mkdir $PKG_ROOT
          git mv temp $PKG_ROOT
          git mv $PKG_ROOT/temp $PKG_ROOT/Assets
          git mv Assets.meta $PKG_ROOT
          git mv Examples $PKG_ROOT
          git mv Examples.meta $PKG_ROOT
          git mv Src $PKG_ROOT
          git mv Src.meta $PKG_ROOT
          git mv README.md $PKG_ROOT || true
          git mv README.md.meta $PKG_ROOT || true
          find $PKG_ROOT/ -name \*.meta >> metaList
        env:
          PKG_ROOT: Assets/UniversalAuthenticatorLibrarySharp
      - name: Make directory for our unity package
        run: mkdir a
      - name: Create Unity Package
        uses: pCYSl5EDgo/create-unitypackage@master
        with:
          package-path: 'a/univeralauthenticatorlibrarysharp.unitypackage'
          include-files: metaList
      - name: Upload package
        uses: actions/upload-artifact@v1
        with:
          name: a
          path: ./a
  
  split-upm:
    name: split upm branch
    runs-on: ubuntu-20.04
    needs: pack-unitypackage
    if: github.event_name == 'push'
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: release_pipeline
        fetch-depth: 0
    - name: split upm branch
      run: |
        git branch -d upm &> /dev/null || echo upm branch not found # recreate the upm branch each time
        git config --global user.name 'github-bot'
        git config --global user.email 'github-bot@users.noreply.github.com'
        git checkout -b upm                                            # checkout the branch
        git mv Examples Samples~
        git rm Examples.meta || true
        git rm -r .github || true
        git commit -am "removed workflow files"
        git push -u origin upm --force                              # commit the branch
  
  release:
    runs-on: ubuntu-20.04
    needs: split-upm
    if: github.event_name == 'push'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Determine version
        run: echo "VERSION=$(git describe --tags --dirty)" >> $GITHUB_ENV
      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1.12.0
        with:
          tag: 1.0.8
          name: Release 1.0.8
          body: ${{ env.VERSION }}
          makeLatest: true
      - name: Download unity package
        uses: actions/download-artifact@v1
        with:
          name: a
          path: ./a
      - name: Upload unity package to release
        uses: Fhwang0926/upload-release-asset@v1.1.17
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_name: a/univeralauthenticatorlibrarysharp.unitypackage # path + filename
          



